# Generated by Django 3.1.7 on 2021-03-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.contact')),
                ('full_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=35)),
                ('region', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=60)),
                ('inhabited_locality', models.CharField(max_length=15)),
            ],
            bases=('main.contact',),
        ),
    ]
