# Generated by Django 3.1.7 on 2021-03-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='inhabited_locality',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(max_length=150),
        ),
    ]
